name: Bump Version

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-bumpr@v1